#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from os.path import dirname, relpath, join

from diylisp.interpreter import interpret_file
from diylisp.repl import repl
from diylisp.types import Environment, LispError

env = Environment()

try:
    interpret_file(join(dirname(relpath(__file__)), 'stdlib.diy'), env)
except LispError as e:
    # Just ignore exceptions from stdlib.
    # These will generally fail until part 6 is done anyways.
    pass

if len(sys.argv) > 1:
    print(interpret_file(sys.argv[1], env))
else:
    repl(env)
